name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install
      - run: yarn tslint
      - run: yarn vscode:prepublish
